name: flutter_time_range
description: A fully customizable flutter widget that allowing users to choose time range (from - to) 
version: 0.1.0
homepage: https://github.com/rymesaint/flutter_time_range

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^2.1.2
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
